#!/usr/bin/env python3
"""
Process duplicate snippets using an LLM for analysis.

This script takes the batches generated by find_duplicates.py,
sends them to an LLM API, and processes the responses to create
consolidated files and identify duplicates.
"""

import os
import sys
import json
import logging
import argparse
from pathlib import Path
from typing import Dict, List, Any, Optional

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Import your existing API functions
try:
    from cleanupx.api import call_xai_api
    from cleanupx.config import XAI_MODEL_TEXT
    API_AVAILABLE = True
except ImportError:
    logger.warning("Could not import cleanupx API. Will use simulated responses.")
    API_AVAILABLE = False

def read_batch_file(batch_file: Path) -> str:
    """Read the content of a batch file."""
    try:
        with open(batch_file, 'r', encoding='utf-8') as f:
            return f.read()
    except Exception as e:
        logger.error(f"Error reading batch file {batch_file}: {e}")
        return ""

def process_batch_with_llm(prompt: str) -> Dict[str, Any]:
    """
    Process a batch using the LLM API.
    
    Args:
        prompt: The prompt to send to the LLM
        
    Returns:
        Parsed JSON response from the LLM
    """
    if not API_AVAILABLE:
        logger.warning("API not available. Returning simulated response.")
        return {
            "groups": [
                {
                    "group_id": "simulated",
                    "analysis": "API not available - this is a simulated response",
                    "duplicates": ["file1.txt", "file2.txt"],
                    "consolidated_file": {
                        "name": "consolidated.txt",
                        "content": "// This is a simulated consolidated file content."
                    }
                }
            ]
        }
    
    # Define the function schema for structured output
    function_schema = {
        "name": "analyze_duplicates",
        "description": "Analyze groups of potential duplicate files and create consolidated versions",
        "parameters": {
            "type": "object",
            "properties": {
                "groups": {
                    "type": "array",
                    "description": "List of analyzed file groups",
                    "items": {
                        "type": "object",
                        "properties": {
                            "group_id": {
                                "type": "string",
                                "description": "ID of the group being analyzed"
                            },
                            "analysis": {
                                "type": "string",
                                "description": "Brief analysis of similarities and differences"
                            },
                            "duplicates": {
                                "type": "array",
                                "description": "List of duplicate file names",
                                "items": {"type": "string"}
                            },
                            "consolidated_file": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string",
                                        "description": "Suggested filename for the consolidated file"
                                    },
                                    "content": {
                                        "type": "string",
                                        "description": "Full content of the consolidated file"
                                    }
                                },
                                "required": ["name", "content"]
                            }
                        },
                        "required": ["group_id", "analysis", "duplicates", "consolidated_file"]
                    }
                }
            },
            "required": ["groups"]
        }
    }
    
    try:
        # Call your existing API
        result = call_xai_api(
            model=XAI_MODEL_TEXT,
            prompt=prompt,
            function_schema=function_schema
        )
        
        # The result should already be parsed if your API returns a dictionary
        return result
    except Exception as e:
        logger.error(f"Error calling LLM API: {e}")
        return {"groups": []}

def save_consolidated_file(file_data: Dict[str, Any], output_dir: Path) -> Path:
    """
    Save a consolidated file to disk.
    
    Args:
        file_data: Dictionary with name and content
        output_dir: Directory to save the file
        
    Returns:
        Path to the saved file
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Create a valid filename
    filename = file_data["name"]
    if not filename:
        filename = "consolidated.txt"
    
    # Ensure the filename has an extension
    if '.' not in filename:
        filename += ".txt"
    
    file_path = output_dir / filename
    
    # If file exists, append a number
    counter = 1
    while file_path.exists():
        stem = Path(filename).stem
        suffix = Path(filename).suffix
        file_path = output_dir / f"{stem}_{counter}{suffix}"
        counter += 1
    
    # Write the file
    try:
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(file_data["content"])
        logger.info(f"Saved consolidated file to {file_path}")
    except Exception as e:
        logger.error(f"Error saving consolidated file: {e}")
        return None
    
    return file_path

def process_llm_response(response: Dict[str, Any], output_dir: Path) -> Dict[str, Any]:
    """
    Process the LLM response and save consolidated files.
    
    Args:
        response: Parsed response from the LLM
        output_dir: Directory to save consolidated files
        
    Returns:
        Dictionary with processing results
    """
    results = {
        "processed_groups": 0,
        "consolidated_files": [],
        "duplicates": {}
    }
    
    # Process each group in the response
    for group in response.get("groups", []):
        group_id = group.get("group_id", "unknown")
        
        # Save the consolidated file
        consolidated_file = group.get("consolidated_file")
        if consolidated_file and "content" in consolidated_file and "name" in consolidated_file:
            file_path = save_consolidated_file(consolidated_file, output_dir)
            
            if file_path:
                # Track the results
                results["processed_groups"] += 1
                results["consolidated_files"].append(str(file_path))
                results["duplicates"][str(file_path)] = group.get("duplicates", [])
                
                # Create a metadata file with the analysis
                meta_path = file_path.with_suffix(file_path.suffix + ".meta.json")
                with open(meta_path, 'w', encoding='utf-8') as f:
                    json.dump({
                        "group_id": group_id,
                        "analysis": group.get("analysis", ""),
                        "duplicates": group.get("duplicates", []),
                        "consolidated_file": str(file_path)
                    }, f, indent=2)
        else:
            logger.warning(f"Group {group_id} has invalid consolidated file data")
    
    return results

def process_batches(batch_dir: Path, output_dir: Path) -> Dict[str, Any]:
    """
    Process all batch files in a directory.
    
    Args:
        batch_dir: Directory containing batch files
        output_dir: Directory to save output files
        
    Returns:
        Dictionary with overall processing results
    """
    # Find all batch files
    batch_files = list(batch_dir.glob("batch_*.txt"))
    logger.info(f"Found {len(batch_files)} batch files to process")
    
    overall_results = {
        "total_batches": len(batch_files),
        "processed_batches": 0,
        "processed_groups": 0,
        "consolidated_files": [],
        "duplicates": {}
    }
    
    # Process each batch
    for batch_file in batch_files:
        logger.info(f"Processing batch file: {batch_file}")
        
        # Read the batch prompt
        prompt = read_batch_file(batch_file)
        if not prompt:
            logger.error(f"Empty or invalid batch file: {batch_file}")
            continue
        
        # Process with LLM
        llm_response = process_batch_with_llm(prompt)
        
        # Process the response
        batch_results = process_llm_response(llm_response, output_dir)
        
        # Update overall results
        overall_results["processed_batches"] += 1
        overall_results["processed_groups"] += batch_results["processed_groups"]
        overall_results["consolidated_files"].extend(batch_results["consolidated_files"])
        overall_results["duplicates"].update(batch_results["duplicates"])
        
        # Save the LLM response
        response_file = batch_file.with_suffix(".response.json")
        with open(response_file, 'w', encoding='utf-8') as f:
            json.dump(llm_response, f, indent=2)
        
    # Save overall results
    results_file = output_dir / "processing_results.json"
    with open(results_file, 'w', encoding='utf-8') as f:
        json.dump({
            "overall_results": overall_results
        }, f, indent=2)
    
    logger.info(f"Batch processing complete. Results saved to {results_file}")
    return overall_results

def main():
    """Main entry point for the script."""
    parser = argparse.ArgumentParser(
        description="Process duplicate snippets using an LLM for analysis"
    )
    parser.add_argument(
        "batch_dir", 
        help="Directory containing batch files generated by find_duplicates.py"
    )
    parser.add_argument(
        "--output-dir", "-o",
        default=None,
        help="Directory to save consolidated files (default: batch_dir/consolidated)"
    )
    
    args = parser.parse_args()
    
    # Parse command line arguments
    batch_dir = Path(args.batch_dir)
    output_dir = Path(args.output_dir) if args.output_dir else batch_dir / "consolidated"
    
    # Ensure directories exist
    if not batch_dir.is_dir():
        logger.error(f"Error: {batch_dir} is not a valid directory")
        sys.exit(1)
    
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Process the batches
    results = process_batches(batch_dir, output_dir)
    
    logger.info(f"Processing complete.")
    logger.info(f"Processed {results['processed_batches']}/{results['total_batches']} batches")
    logger.info(f"Created {len(results['consolidated_files'])} consolidated files")

if __name__ == "__main__":
    main() 